version: '3'
services:
  mockit-routes:
    image: 'mockit-routes'
    build: 'mockit-routes'
    ports:
      - 3000:3000
    volumes:
      - ./configuration/routes.json:/usr/src/mockit-routes/configuration/routes.json
