branch-defaults:
  default:
    environment: Coeusproduction-env
environment-defaults:
  Coeusproduction-env:
    branch: null
    repository: null
global:
  application_name: coeus-production
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
deploy:
  artifact: Dockerrun.aws.json
